FIPSCODES = {
      "02"	:	  "AK"	,
     "01"	:	  "AL"	,
     "05"	:	  "AR"	,
     "60"	:	  "AS"	,
     "04"	:	  "AZ"	,
     "06"	:	  "CA"	,
     "08"	:	  "CO"	,
     "09"	:	  "CT"	,
     "11"	:	  "DC"	,
     "10"	:	  "DE"	,
     "12"	:	  "FL"	,
     "13"	:	  "GA"	,
     "66"	:	  "GU"	,
     "15"	:	  "HI"	,
     "19"	:	  "IA"	,
     "16"	:	  "ID"	,
     "17"	:	  "IL"	,
     "18"	:	  "IN"	,
     "20"	:	  "KS"	,
     "21"	:	  "KY"	,
     "22"	:	  "LA"	,
     "25"	:	  "MA"	,
     "24"	:	  "MD"	,
     "23"	:	  "ME"	,
     "26"	:	  "MI"	,
     "27"	:	  "MN"	,
     "29"	:	  "MO"	,
     "28"	:	  "MS"	,
     "30"	:	  "MT"	,
     "37"	:	  "NC"	,
     "38"	:	  "ND"	,
     "31"	:	  "NE"	,
     "33"	:	  "NH"	,
     "34"	:	  "NJ"	,
     "35"	:	  "NM"	,
     "32"	:	  "NV"	,
     "36"	:	  "NY"	,
     "39"	:	  "OH"	,
     "40"	:	  "OK"	,
     "41"	:	  "OR"	,
     "42"	:	  "PA"	,
     "72"	:	  "PR"	,
     "44"	:	  "RI"	,
     "45"	:	  "SC"	,
     "46"	:	  "SD"	,
     "47"	:	  "TN"	,
     "48"	:	  "TX"	,
     "49"	:	  "UT"	,
     "51"	:	  "VA"	,
     "78"	:	  "VI"	,
     "50"	:	  "VT"	,
     "53"	:	  "WA"	,
     "55"	:	  "WI"	,
     "54"	:	  "WV"	,
     "56"	:	  "WY"
  };

USGS_alt_meth_cd = {
    "A" :"Altimeter",
    "D":"Differentially corrected Global Positioning System",
    "F":"Survey-grade GPSF",
    "I":"Interferometric Synthetic Aperture Radar, airplane",
    "J":"Light Detection And Ranging, airplane",
    "L":"Level or other surveyed method",
    "M":"Interpolated from topographic map",
    "N":"Interpolated from Digital Elevation Model",
    "R":"Reported method of determination",
    "W":"GNSS1 - Level 1 Quality Survey Grade Global Navigation Satellite System",
    "X":"GNSS2 - Level 2 Quality Survey Grade Global Navigation Satellite System",
    "Y":"GNSS3 - Level 3 Quality Survey Grade Global Navigation Satellite System",
    "Z":"GNSS4 - Level 4 Quality Survey Grade Global Navigation Satellite System"
};

USGS_coord_acy_cd = {
    "H":"	Accurate to + or - .01 sec (Differentially-Corrected GPS)",
    "1":"	Accurate to + or - .1  sec (Differentially-Corrected GPS)",
    "5":"	Accurate to + or - .5  sec (PLGR/PPS GPS)",
    "M":"	Accurate to + or - 1   min",
    "S":"Accurate to + or - 1   sec",
    "T":"Accurate to + or - 10  sec",
    "R":"Accurate to + or - 3   sec (SPS GPS)",
    "F":"Accurate to + or - 5   sec",
    "B":"Level 1 survey-grade GPS",
    "C":"Level 2 survey-grade GPS",
    "D":"Level 3 survey-grade GPS",
    "E":"Level 4 survey-grade GPS",
    "U":"Unknown or unspecified"
}
